* Switch from /bin/sh to /bin/bash * Add restore functionality to the various modules * Create temporary directories with mktempp -d * Also copy sources.list-files and apt-key files in dpkg * Use apt-get dselect-upgrade in dpkg * Set the right DEBIAN_FRONTEND

diff --git a/openapp-restore b/openapp-restore
--- a/openapp-restore
+++ b/openapp-restore
@@ -1,43 +1,45 @@
-#!/bin/sh
+#!/bin/bash
 
 ###
-# This script will look for scripts to run to create a backup of the system
-# which should be suitable for restoring and migrating to another machine
+# This script will look for scripts to run to restore a system based on the
+# backup-file created by openapp-backup.
 ###
 
 . /usr/src/openapp-backup/includes/index
 
+[ -z $1 ] && fatal "You should enter an argument, the file you want to restore from"
+[ -f ${1} ] || fatal "Cannot find the file you want me to use to restore"
+
 [ `id -u` -gt 0 ]  && fatal "This script must be run as root"
 
-BACKUPDIR=/tmp/openapp-backup-$$
+BACKUPDIR=$(mktemp -d)
 MODULEDIR=/usr/src/openapp-backup/modules
 WARNINGS=0
 FATALS=0
 
 ###
-# Create a dir in which we will create the backup
-mkdir ${BACKUPDIR}
+# Extract the tar-file in the tempdir
+cd ${BACKUPDIR}
+tar --numeric-owner -zxf ${1}
 
 ###
 # Now look for specific modules to backup
 MODULES=$(grep -H '^# Prio' ${MODULEDIR}/* | sort -k 3 -n | cut -f 1 -d :)
 for SCRIPT in $MODULES; do
-    OUTPUT=$(${SCRIPT} ${BACKUPDIR} backup 2> /dev/null)
+    SCRIPTNAME=$(basename ${SCRIPT})
+    ###
+    # Don't run this script if the backup doesn't contain a dir for it.
+    [ -d ${BACKUPDIR}/${SCRIPTNAME} ] || continue
+
+    echo "Running ${SCRIPTNAME}..."
+    OUTPUT=$(${SCRIPT} ${BACKUPDIR}/${SCRIPTNAME} restore 2> /dev/null)
     [ -z "${OUTPUT}" ] || warning "${SCRIPT}: $OUTPUT"
 done
 
+rm -rf ${BACKUPDIR}
+
 if [ $WARNINGS -eq 0 -a $FATALS -eq 0 ]; then
     echo "All went well"
-    echo "Creating tar-file"
-    tar zcf /tmp/openapp-backup.tar.gz ${BACKUPDIR}/ || warning "Could not create tar file"
-
-    rm -rf ${BACKUPDIR};
-    if [ $WARNINGS -eq 0 -a $FATALS -eq 0 ]; then
-        echo "Your backupfile is: /tmp/openapp-backup.tar.gz"
-    else
-        echo "Something went wrong while creating the tar file. Please investigate"
-        exit 1
-    fi
 else
     echo "There where $FATALS fatal errors and $WARNINGS warnings"
     exit 1
