bash doesn't reread MODULES. So run dpkg-selections and etc first (manually)

diff --git a/openapp-restore b/openapp-restore
--- a/openapp-restore
+++ b/openapp-restore
@@ -33,35 +33,36 @@ tar --numeric-owner -zxf ${1}
 
 ###
 # Make sure we run these first
-MODULES="${BASEMODULES}/dpkg-selections ${BASEMODULES}/etc"
+echo "Running dpkg-selections"
+OUTPUT=$(${BASEMODULES}/dpkg-selections ${BACKUPDIR}/${SCRIPTNAME} restore 2> /dev/null)
+[ -z "${OUTPUT}" ] || warning "${SCRIPT}: $OUTPUT"
+OUTPUT=
+echo "Running etc"
+OUTPUT=$(${BASEMODULES}/etc ${BACKUPDIR}/${SCRIPTNAME} restore 2> /dev/null)
+[ -z "${OUTPUT}" ] || warning "${SCRIPT}: $OUTPUT"
+OUTPUT=
 
 ###
 # Now look for specific modules to restore from
-MODULES="${MODULES} "$(grep -H '^# Prio' "${MODULEDIR}"/* 2>/dev/null | sort -k 3 -n | cut -f 1 -d :)
+MODULES=$(grep -H '^# Prio' "${MODULEDIR}"/* 2>/dev/null | sort -k 3 -n | cut -f 1 -d :)
 for SCRIPT in $MODULES; do
-    SCRIPTNAME=$(basename ${SCRIPT})
-    ###
-    # Don't run this script if the backup doesn't contain a dir for it.
-    [ -d ${BACKUPDIR}/${SCRIPTNAME} ] || continue
-
-
-    echo "Running ${SCRIPTNAME}..."
-    OUTPUT=$(${SCRIPT} ${BACKUPDIR}/${SCRIPTNAME} restore 2> /dev/null)
-
+	SCRIPTNAME=$(basename ${SCRIPT})
 	###
-	# After we ran etc (which restored the symlinks of the box we're restoring)
-	# refresh the modulelist. This will cause dpkg and etc to run again, but
-	# that's not really an issue.
-	[ "${SCRIPTNAME}" = "etc" ] && MODULES=$(grep -H '^# Prio' "${MODULEDIR}"/* 2>/dev/null | sort -k 3 -n | cut -f 1 -d :)
+	# Don't run this script if the backup doesn't contain a dir for it.
+	[ -d ${BACKUPDIR}/${SCRIPTNAME} ] || continue
 
-    [ -z "${OUTPUT}" ] || warning "${SCRIPT}: $OUTPUT"
+	echo "Running ${SCRIPTNAME}..."
+	OUTPUT=$(${SCRIPT} ${BACKUPDIR}/${SCRIPTNAME} restore 2> /dev/null)
+
+	[ -z "${OUTPUT}" ] || warning "${SCRIPT}: $OUTPUT"
 done
 
 rm -rf ${BACKUPDIR}
 
 if [ $WARNINGS -eq 0 -a $FATALS -eq 0 ]; then
-    echo "All went well"
+	echo "All went well"
 else
-    echo "There where $FATALS fatal errors and $WARNINGS warnings"
-    exit 1
+	echo "There where $FATALS fatal errors and $WARNINGS warnings"
+	exit 1
 fi
+
